//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021. 11. 18. 9:34:29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Oltas
{
    public partial class Institute {

        public Institute()
        {
            this.Patients = new List<Patient>();
            this.Physicians = new List<Physician>();
            OnCreated();
        }

        public virtual int id { get; set; }

        public virtual string instituteName { get; set; }

        public virtual int zip { get; set; }

        public virtual IList<Patient> Patients { get; set; }

        public virtual IList<Physician> Physicians { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
