//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021. 11. 20. 0:06:13
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Oltas
{
    public partial class Oltott {

        public Oltott()
        {
            OnCreated();
        }

        public virtual int id { get; set; }

        public virtual string patient { get; set; }

        public virtual int taj { get; set; }

        public virtual string oltanyag { get; set; }

        public virtual string serialnumber { get; set; }

        public virtual DateTime time { get; set; }

        public virtual string orvosnev { get; set; }

        public virtual int orvospecset { get; set; }

        public virtual string intezmeny { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
