//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021. 11. 17. 9:56:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Oltas
{
    public partial class Physician {

        public Physician()
        {
            this.Institutes = new List<Institute>();
            this.Patients = new List<Patient>();
            OnCreated();
        }

        public virtual int pecsetszam { get; set; }

        public virtual string dr_name { get; set; }

        public virtual IList<Institute> Institutes { get; set; }

        public virtual IList<Patient> Patients { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
